var finddir,list,list2,i,fn;

finddir=working_directory

if (!file_exists("readme.md"))
    finddir=directory_previous(finddir)

tmpdir=finddir+"\tutorial\"

finddir=directory_previous(finddir)

list=file_find_list(finddir,"*",fa_directory,false)
list2=dslist()

i=0 repeat (ds_list_size(list)) {
    fn=ds_list_find_value(list,i)+"\johnny.cfg"
    if (file_exists(fn)) ds_list_add(list2,fn)
i+=1}

if (!ds_list_size(list2)) {
    show_message("Johnny v0.21#GM8.2 documentation generator##Run in the github folder.")
    exit
}

johnny_exts=""
johnny_names=""
johnny_descs=""

i=0 repeat (ds_list_size(list2)) {
    process_johnny_file(ds_list_find_value(list2,i),finddir)
i+=1}

johnny_insert='
    //Arrays generated by Johnny 0.21
    func_exts=[
        '+johnny_exts+'
    ];
    
    func_name_table=[
        '+johnny_names+'
    ];
    
    func_desc_table=[
        '+johnny_descs+'
    ];   
'

str=string_replace(file_text_read_all(tmpdir+"\template.html"),"/*johnny*/",johnny_insert)
file_text_write_all("C:\path\gamemaker\tutorials\GM82 Documentation\page01.html",str)

game_end()
